spring.application.name=digital-wallet-backend


natwest.client-id=
natwest.client-secret=
natwest.redirect-uri=
natwest.psu-username=

natwest.token-url=
natwest.authorize-url=
natwest.resource-url=
